### ISSUE TITLE
Fix vulnerabilities in dependency

### ISSUE THREAD

**Issue by jeyemwey** [jeyemwey/mumbleRadio#3]
Hi @all, I have no idea how you would fix this, but I got this email this morning from GitHub.

![image](https://user-images.githubusercontent.com/2796271/46664942-a826a900-cbc2-11e8-8bb1-89d9ec9b2f5e.png)

I would love if somebody could fix this and I could learn from your contribution.

**Comment by Snelius30** [comment]
Well. I can do that i guess.

**Comment by dnivra26** [comment]
i think protobufjs is a transitive dependency, it is being used by your direct dependency mumble. you can raise an issue with them to update protobufjs version.

**Comment by jeyemwey** [comment]
@dnivra26 Can you oversee whether #4 would fix the issue?

**Comment by jeyemwey** [comment]
Rantanen bumped the protobufjs to ^5, so this should fix the issue. https://github.com/Rantanen/node-mumble/issues/114#issuecomment-435159521

- [ ] Depend on the newer version of mumble.
